In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ds=pd.read_csv(r"C:\Users\Parth\Downloads\placement-dataset.csv")

In [3]:
ds.head(4)

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1

In [4]:

ds.columns

Index(['Unnamed: 0', 'cgpa', 'iq', 'placement'], dtype='object')

In [5]:
ds.drop("Unnamed: 0",axis=1,inplace=True)

In [6]:
ds

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

In [7]:
ds.isnull().sum()

cgpa         0
iq           0
placement    0
dtype: int64

In [8]:
ds["placement"].value_counts()

placement
1    50
0    50
Name: count, dtype: int64

In [11]:
from mlxtend.plotting import plot_decision_regions

In [14]:
from jupyter_client.kernelspec import KernelSpecManager

ksm = KernelSpecManager()
print(ksm.find_kernel_specs())

{'python313': 'C:\\Users\\Parth\\AppData\\Roaming\\jupyter\\kernels\\python313', 'your-env-name': 'C:\\Users\\Parth\\AppData\\Roaming\\jupyter\\kernels\\your-env-name', 'python3': 'C:\\Users\\Parth\\AppData\\Roaming\\Python\\share\\jupyter\\kernels\\python3'}

In [15]:
import pkg_resources

installed_packages = sorted(["%s==%s" % (i.key, i.version) for i in pkg_resources.working_set])
for pkg in installed_packages:
    print(pkg)

anyio==4.9.0
argon2-cffi-bindings==21.2.0
argon2-cffi==23.1.0
arrow==1.3.0
asttokens==3.0.0
async-lru==2.0.5
attrs==25.3.0
autocommand==2.2.2
babel==2.17.0
backports.tarfile==1.2.0
beautifulsoup4==4.13.4
bleach==6.2.0
certifi==2025.4.26
cffi==1.17.1
charset-normalizer==3.4.2
colorama==0.4.6
comm==0.2.2
contourpy==1.3.2
cycler==0.12.1
debugpy==1.8.14
decorator==5.2.1
defusedxml==0.7.1
executing==2.2.0
fastjsonschema==2.21.1
fonttools==4.58.0
fqdn==1.5.1
h11==0.16.0
httpcore==1.0.9
httpx==0.28.1
idna==3.10
imbalanced-learn==0.13.0
imblearn==0.0
importlib-metadata==8.0.0
inflect==7.3.1
ipykernel==6.29.5
ipython-genutils==0.2.0
ipython-pygments-lexers==1.1.1
ipython==9.2.0
isoduration==20.11.0
jaraco.collections==5.1.0
jaraco.context==5.3.0
jaraco.functools==4.0.1
jaraco.text==3.12.1
jedi==0.19.2
jinja2==3.1.6
joblib==1.5.0
json5==0.12.0
jsonpointer==3.0.0
jsonschema-specifications==2025.4.1
jsonschema==4.23.0
jupyter-client==8.6.3
jupyter-contrib-core==0.4.2
jupyter-contrib-nbextensions==0.7.0
jupyter-core==5.7.2
jupyter-events==0.12.0
jupyter-highlight-selected-word==0.2.0
jupyter-lsp==2.2.5
jupyter-nbextensions-configurator==0.6.4
jupyter-server-terminals==0.5.3
jupyter-server==2.16.0
jupyterlab-pygments==0.3.0
jupyterlab-server==2.27.3
jupyterlab==4.4.2
kiwisolver==1.4.8
lxml==5.4.0
markupsafe==3.0.2
matplotlib-inline==0.1.7
matplotlib==3.10.3
mistune==3.1.3
mlxtend==0.23.4
more-itertools==10.3.0
nbclient==0.10.2
nbconvert==7.16.6
nbformat==5.10.4
nest-asyncio==1.6.0
notebook-shim==0.2.4
notebook==7.4.2
numpy==2.2.5
overrides==7.7.0
packaging==25.0
pandas==2.2.3
pandocfilters==1.5.1
parso==0.8.4
pillow==11.2.1
pip==25.1.1
platformdirs==4.3.8
prometheus-client==0.21.1
prompt-toolkit==3.0.51
psutil==7.0.0
pure-eval==0.2.3
pycparser==2.22
pygments==2.19.1
pyparsing==3.2.3
python-dateutil==2.9.0.post0
python-json-logger==3.3.0
pytz==2025.2
pywin32==310
pywinpty==2.0.15
pyyaml==6.0.2
pyzmq==26.4.0
referencing==0.36.2
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.24.0
scikit-learn==1.6.1
scipy==1.15.3
seaborn==0.13.2
send2trash==1.8.3
setuptools==80.4.0
six==1.17.0
sklearn-compat==0.1.3
sniffio==1.3.1
soupsieve==2.7
stack-data==0.6.3
terminado==0.18.1
threadpoolctl==3.6.0
tinycss2==1.4.0
tomli==2.0.1
tornado==6.4.2
traitlets==5.14.3
typeguard==4.3.0
types-python-dateutil==2.9.0.20241206
typing-extensions==4.13.2
tzdata==2025.2
uri-template==1.3.0
urllib3==2.4.0
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
wheel==0.45.1
zipp==3.19.2

C:\Users\Parth\AppData\Local\Temp\ipykernel_8952\2627014643.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

In [16]:
import sys
print(sys.version)

3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]